spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:29092
      group-id: testgroup2
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: imageNameMessage:org.maxpri.blps.model.dto.messages.ImageNameMessage
        spring.json.trusted.packages: "*"
    producer:
      acks: -1
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: imageMessage:org.maxpri.blps.model.dto.messages.ImageMessage

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/blps
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/blps
    baselineOnMigrate: true
  data:
    elasticsearch:
      repositories:
        enabled: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8282/realms/blps
          jwk-set-uri: http://localhost:8282/realms/blps/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: backend
            client-secret: O2sknqBYnHTE8fitIjr7aWegnUe9B6P1


maxpri:
  app:
    jwtExpirationMs: 10000000
    jwtSecret: ======================MAXPRI=TEST===========================
keycloak:
  server-url: http://localhost:8282
  realm: blps
  username: admin
  password: admin