version: '3'

services:
  article:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: article
#    volumes:
#      - ./docker-entrypoint-initdb.d.article:/docker-entrypoint-initdb.d
    command:
      - "postgres"
      - "-c"
      - "max_prepared_transactions=100"


  art-image:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: art-image
#    volumes:
#      - ./docker-entrypoint-initdb.d.art-image:/docker-entrypoint-initdb.d
    command:
      - "postgres"
      - "-c"
      - "max_prepared_transactions=100"
